import type { Specialist, Booking, Review, Notification } from "./types";

export const mockSpecialists: Specialist[] = [
  {
    id: "sp1",
    name: "Amara Johnson",
    email: "amara@example.com",
    phone: "+1 555-0101",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amara",
    role: "specialist",
    bio: "Professional hair stylist with 8 years of experience specializing in natural hair, braids, and protective styles. I bring the salon experience to your home!",
    specialties: ["Natural Hair", "Braids", "Locs", "Protective Styles"],
    services: [
      {
        id: "s1",
        name: "Box Braids",
        description: "Full head box braids with extensions",
        duration: 240,
        price: 150,
        category: "hair",
      },
      {
        id: "s2",
        name: "Wash & Style",
        description: "Shampoo, condition, and style",
        duration: 90,
        price: 65,
        category: "hair",
      },
      {
        id: "s3",
        name: "Loc Maintenance",
        description: "Retwist and moisturize locs",
        duration: 120,
        price: 80,
        category: "hair",
      },
    ],
    location: {
      address: "123 Beauty Lane",
      city: "Atlanta, GA",
      lat: 33.749,
      lng: -84.388,
    },
    rating: 4.9,
    reviewCount: 127,
    isAvailable: true,
    yearsExperience: 8,
    portfolio: [
      "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400",
      "https://images.unsplash.com/photo-1560869713-7d0a29430803?w=400",
      "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=400",
    ],
    availability: {
      monday: [{ start: "09:00", end: "18:00" }],
      tuesday: [{ start: "09:00", end: "18:00" }],
      wednesday: [{ start: "09:00", end: "18:00" }],
      thursday: [{ start: "09:00", end: "18:00" }],
      friday: [{ start: "09:00", end: "20:00" }],
      saturday: [{ start: "08:00", end: "16:00" }],
      sunday: [],
    },
    priceRange: { min: 65, max: 150 },
    verified: true,
    createdAt: "2023-01-15T00:00:00Z",
  },
  {
    id: "sp2",
    name: "Sofia Martinez",
    email: "sofia@example.com",
    phone: "+1 555-0102",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia",
    role: "specialist",
    bio: "Certified nail technician and nail artist. I create stunning nail designs that express your personality. Gel, acrylic, and nail art specialist.",
    specialties: ["Gel Nails", "Acrylic", "Nail Art", "Manicure", "Pedicure"],
    services: [
      {
        id: "s4",
        name: "Gel Manicure",
        description: "Long-lasting gel polish manicure",
        duration: 60,
        price: 45,
        category: "nails",
      },
      {
        id: "s5",
        name: "Acrylic Full Set",
        description: "Full set of acrylic nails with design",
        duration: 90,
        price: 75,
        category: "nails",
      },
      {
        id: "s6",
        name: "Pedicure",
        description: "Relaxing pedicure with polish",
        duration: 60,
        price: 40,
        category: "nails",
      },
      {
        id: "s7",
        name: "Nail Art",
        description: "Custom nail art designs",
        duration: 30,
        price: 25,
        category: "nails",
      },
    ],
    location: {
      address: "456 Glamour Ave",
      city: "Atlanta, GA",
      lat: 33.762,
      lng: -84.375,
    },
    rating: 4.8,
    reviewCount: 89,
    isAvailable: true,
    yearsExperience: 5,
    portfolio: [
      "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400",
      "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400",
    ],
    availability: {
      monday: [{ start: "10:00", end: "19:00" }],
      tuesday: [{ start: "10:00", end: "19:00" }],
      wednesday: [],
      thursday: [{ start: "10:00", end: "19:00" }],
      friday: [{ start: "10:00", end: "19:00" }],
      saturday: [{ start: "09:00", end: "17:00" }],
      sunday: [{ start: "11:00", end: "15:00" }],
    },
    priceRange: { min: 25, max: 75 },
    verified: true,
    createdAt: "2023-03-20T00:00:00Z",
  },
  {
    id: "sp3",
    name: "Priya Patel",
    email: "priya@example.com",
    phone: "+1 555-0103",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
    role: "specialist",
    bio: "Professional makeup artist for weddings, events, and everyday glam. I use only premium products to create flawless looks that last all day.",
    specialties: ["Bridal Makeup", "Event Makeup", "Airbrush", "Natural Looks"],
    services: [
      {
        id: "s8",
        name: "Bridal Makeup",
        description: "Full bridal makeup with trial",
        duration: 180,
        price: 250,
        category: "makeup",
      },
      {
        id: "s9",
        name: "Event Makeup",
        description: "Glamorous makeup for special events",
        duration: 90,
        price: 120,
        category: "makeup",
      },
      {
        id: "s10",
        name: "Natural Everyday Look",
        description: "Light, natural makeup for daily wear",
        duration: 45,
        price: 60,
        category: "makeup",
      },
    ],
    location: {
      address: "789 Radiance Blvd",
      city: "Atlanta, GA",
      lat: 33.755,
      lng: -84.395,
    },
    rating: 5.0,
    reviewCount: 203,
    isAvailable: true,
    yearsExperience: 10,
    portfolio: [
      "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=400",
      "https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?w=400",
    ],
    availability: {
      monday: [{ start: "08:00", end: "20:00" }],
      tuesday: [{ start: "08:00", end: "20:00" }],
      wednesday: [{ start: "08:00", end: "20:00" }],
      thursday: [{ start: "08:00", end: "20:00" }],
      friday: [{ start: "08:00", end: "22:00" }],
      saturday: [{ start: "07:00", end: "22:00" }],
      sunday: [{ start: "09:00", end: "18:00" }],
    },
    priceRange: { min: 60, max: 250 },
    verified: true,
    createdAt: "2022-06-10T00:00:00Z",
  },
  {
    id: "sp4",
    name: "Keisha Williams",
    email: "keisha@example.com",
    phone: "+1 555-0104",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Keisha",
    role: "specialist",
    bio: "Licensed esthetician specializing in skincare treatments, facials, and waxing. Your skin deserves the best care, and I bring it to your door.",
    specialties: ["Facials", "Chemical Peels", "Waxing", "Microdermabrasion"],
    services: [
      {
        id: "s11",
        name: "Deep Cleansing Facial",
        description: "Thorough cleansing and hydration treatment",
        duration: 75,
        price: 85,
        category: "skincare",
      },
      {
        id: "s12",
        name: "Full Body Wax",
        description: "Complete body waxing service",
        duration: 120,
        price: 130,
        category: "waxing",
      },
      {
        id: "s13",
        name: "Eyebrow Shaping",
        description: "Wax and thread eyebrow shaping",
        duration: 30,
        price: 25,
        category: "eyebrows",
      },
    ],
    location: {
      address: "321 Glow Street",
      city: "Atlanta, GA",
      lat: 33.741,
      lng: -84.381,
    },
    rating: 4.7,
    reviewCount: 156,
    isAvailable: false,
    yearsExperience: 6,
    portfolio: [
      "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400",
    ],
    availability: {
      monday: [],
      tuesday: [{ start: "09:00", end: "17:00" }],
      wednesday: [{ start: "09:00", end: "17:00" }],
      thursday: [{ start: "09:00", end: "17:00" }],
      friday: [{ start: "09:00", end: "17:00" }],
      saturday: [{ start: "10:00", end: "15:00" }],
      sunday: [],
    },
    priceRange: { min: 25, max: 130 },
    verified: true,
    createdAt: "2022-11-05T00:00:00Z",
  },
  {
    id: "sp5",
    name: "Zara Thompson",
    email: "zara@example.com",
    phone: "+1 555-0105",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Zara",
    role: "specialist",
    bio: "Certified lash technician offering classic, hybrid, and volume lash extensions. Wake up beautiful every day with stunning lashes!",
    specialties: ["Classic Lashes", "Volume Lashes", "Hybrid", "Lash Lift"],
    services: [
      {
        id: "s14",
        name: "Classic Lash Extensions",
        description: "Natural-looking classic lash extensions",
        duration: 90,
        price: 95,
        category: "lashes",
      },
      {
        id: "s15",
        name: "Volume Lashes",
        description: "Full, dramatic volume lash set",
        duration: 120,
        price: 130,
        category: "lashes",
      },
      {
        id: "s16",
        name: "Lash Lift & Tint",
        description: "Lift and tint your natural lashes",
        duration: 60,
        price: 75,
        category: "lashes",
      },
    ],
    location: {
      address: "654 Lash Lane",
      city: "Atlanta, GA",
      lat: 33.768,
      lng: -84.362,
    },
    rating: 4.6,
    reviewCount: 74,
    isAvailable: true,
    yearsExperience: 3,
    portfolio: [
      "https://images.unsplash.com/photo-1583001931096-959e9a1a6223?w=400",
    ],
    availability: {
      monday: [{ start: "10:00", end: "18:00" }],
      tuesday: [{ start: "10:00", end: "18:00" }],
      wednesday: [{ start: "10:00", end: "18:00" }],
      thursday: [{ start: "10:00", end: "18:00" }],
      friday: [{ start: "10:00", end: "18:00" }],
      saturday: [{ start: "09:00", end: "16:00" }],
      sunday: [],
    },
    priceRange: { min: 75, max: 130 },
    verified: false,
    createdAt: "2024-01-20T00:00:00Z",
  },
  {
    id: "sp6",
    name: "Maya Chen",
    email: "maya@example.com",
    phone: "+1 555-0106",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maya",
    role: "specialist",
    bio: "Relaxation massage therapist specializing in Swedish, deep tissue, and hot stone massages. Let me melt away your stress at home.",
    specialties: ["Swedish Massage", "Deep Tissue", "Hot Stone", "Aromatherapy"],
    services: [
      {
        id: "s17",
        name: "Swedish Massage (60 min)",
        description: "Relaxing full body Swedish massage",
        duration: 60,
        price: 90,
        category: "massage",
      },
      {
        id: "s18",
        name: "Deep Tissue Massage",
        description: "Therapeutic deep tissue massage",
        duration: 90,
        price: 120,
        category: "massage",
      },
      {
        id: "s19",
        name: "Hot Stone Massage",
        description: "Luxurious hot stone therapy",
        duration: 90,
        price: 140,
        category: "massage",
      },
    ],
    location: {
      address: "987 Serenity Way",
      city: "Atlanta, GA",
      lat: 33.758,
      lng: -84.402,
    },
    rating: 4.9,
    reviewCount: 112,
    isAvailable: true,
    yearsExperience: 7,
    portfolio: [
      "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400",
    ],
    availability: {
      monday: [{ start: "09:00", end: "19:00" }],
      tuesday: [{ start: "09:00", end: "19:00" }],
      wednesday: [{ start: "09:00", end: "19:00" }],
      thursday: [{ start: "09:00", end: "19:00" }],
      friday: [{ start: "09:00", end: "19:00" }],
      saturday: [{ start: "10:00", end: "17:00" }],
      sunday: [{ start: "11:00", end: "16:00" }],
    },
    priceRange: { min: 90, max: 140 },
    verified: true,
    createdAt: "2023-05-12T00:00:00Z",
  },
];

export const mockBookings: Booking[] = [
  {
    id: "b1",
    clientId: "client1",
    clientName: "Jessica Brown",
    clientAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica",
    specialistId: "sp1",
    specialistName: "Amara Johnson",
    specialistAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amara",
    service: {
      id: "s1",
      name: "Box Braids",
      description: "Full head box braids with extensions",
      duration: 240,
      price: 150,
      category: "hair",
    },
    date: "2026-03-05",
    time: "10:00",
    status: "confirmed",
    notes: "Please bring your own extensions if possible",
    address: "123 Client Street, Atlanta, GA",
    totalAmount: 150,
    createdAt: "2026-02-25T10:00:00Z",
    updatedAt: "2026-02-25T14:00:00Z",
  },
  {
    id: "b2",
    clientId: "client1",
    clientName: "Jessica Brown",
    clientAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica",
    specialistId: "sp2",
    specialistName: "Sofia Martinez",
    specialistAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia",
    service: {
      id: "s4",
      name: "Gel Manicure",
      description: "Long-lasting gel polish manicure",
      duration: 60,
      price: 45,
      category: "nails",
    },
    date: "2026-03-10",
    time: "14:00",
    status: "pending",
    address: "123 Client Street, Atlanta, GA",
    totalAmount: 45,
    createdAt: "2026-02-26T09:00:00Z",
    updatedAt: "2026-02-26T09:00:00Z",
  },
  {
    id: "b3",
    clientId: "client1",
    clientName: "Jessica Brown",
    clientAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica",
    specialistId: "sp3",
    specialistName: "Priya Patel",
    specialistAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
    service: {
      id: "s9",
      name: "Event Makeup",
      description: "Glamorous makeup for special events",
      duration: 90,
      price: 120,
      category: "makeup",
    },
    date: "2026-02-20",
    time: "09:00",
    status: "completed",
    address: "123 Client Street, Atlanta, GA",
    totalAmount: 120,
    paymentId: "pay_123",
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-02-20T12:00:00Z",
  },
];

export const mockReviews: Review[] = [
  {
    id: "r1",
    bookingId: "b_old1",
    clientId: "client2",
    clientName: "Tanya Davis",
    clientAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tanya",
    specialistId: "sp1",
    rating: 5,
    comment:
      "Amara is absolutely amazing! She did my box braids perfectly and was so professional. Will definitely book again!",
    createdAt: "2026-02-10T00:00:00Z",
  },
  {
    id: "r2",
    bookingId: "b_old2",
    clientId: "client3",
    clientName: "Rachel Green",
    clientAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rachel",
    specialistId: "sp1",
    rating: 5,
    comment:
      "Best hair stylist I've ever had! She came to my home and made me feel like royalty. My locs look incredible.",
    createdAt: "2026-01-28T00:00:00Z",
  },
  {
    id: "r3",
    bookingId: "b_old3",
    clientId: "client4",
    clientName: "Monica Lee",
    clientAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Monica",
    specialistId: "sp2",
    rating: 5,
    comment:
      "Sofia's nail art is out of this world! She created exactly what I wanted and the gel lasted 3 weeks!",
    createdAt: "2026-02-05T00:00:00Z",
  },
  {
    id: "r4",
    bookingId: "b_old4",
    clientId: "client5",
    clientName: "Aisha Okafor",
    clientAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha",
    specialistId: "sp3",
    rating: 5,
    comment:
      "Priya did my wedding makeup and I looked absolutely stunning! She's a true artist. Highly recommend!",
    createdAt: "2026-01-15T00:00:00Z",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    userId: "client1",
    title: "Booking Confirmed! 🎉",
    message: "Amara Johnson confirmed your Box Braids appointment on March 5th at 10:00 AM",
    type: "booking",
    read: false,
    createdAt: "2026-02-25T14:00:00Z",
    bookingId: "b1",
  },
  {
    id: "n2",
    userId: "client1",
    title: "Booking Request Sent",
    message: "Your booking request for Gel Manicure with Sofia Martinez is pending confirmation",
    type: "booking",
    read: true,
    createdAt: "2026-02-26T09:00:00Z",
    bookingId: "b2",
  },
  {
    id: "n3",
    userId: "client1",
    title: "Payment Successful ✅",
    message: "Payment of $120 for Event Makeup with Priya Patel was successful",
    type: "payment",
    read: true,
    createdAt: "2026-02-20T12:30:00Z",
    bookingId: "b3",
  },
];

export const currentUser = {
  id: "client1",
  name: "Jessica Brown",
  email: "jessica@example.com",
  phone: "+1 555-9999",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica",
  role: "client" as const,
  createdAt: "2025-01-01T00:00:00Z",
};

export const currentSpecialist = mockSpecialists[0];
